- name: Prepare ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Generate node environments
      changed_when: true
      ansible.builtin.command:
        cmd: ./configure.sh

    - name: Create metrics directory
      ansible.builtin.file:
        path: metrics
        state: directory
        mode: "0755"

- name: Prepare fledger nodes
  hosts: nodes
  become: true
  tasks:
    - name: Stop nodes
      ansible.builtin.script: ../playbook/scripts/stop-nodes.sh

    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/
        mode: preserve
      loop:
        - ~/fledger
        - ../playbook/fledger.service

    - name: Copy environment
      ansible.builtin.copy:
        src: "env.systemd/{{ inventory_hostname }}/"
        dest: ~/env.systemd
        mode: preserve

- name: Prepare central node
  hosts: central
  become: true
  tasks:
    - name: Disable ip forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 0
        sysctl_set: true
        state: present
        reload: true

    - name: Stop central
      ansible.builtin.script: ../playbook/scripts/stop-central.sh
      register: out

    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/
        mode: preserve
      loop:
        - ~/fledger
        - ~/flsignal
        - ../playbook/flsignal.service
        - ../playbook/flrealm.service
        - env.systemd/central

    - name: Start central
      ansible.builtin.script: ../playbook/scripts/start-central.sh
      register: out

- name: Run the simulation
  hosts: nodes
  become: true
  timeout: 300
  tasks:
    - name: Start nodes
      ansible.builtin.script: ../playbook/scripts/start-nodes.sh

    - name: Wait for simulation end
      ansible.builtin.script: ../playbook/scripts/wait-nodes.sh


# Must remain separate so it runs even if the simulation fails
- name: Download metrics
  hosts: nodes
  become: true
  tasks:
    - name: Assemble metrics on node
      ansible.builtin.script: ../playbook/scripts/assemble-metrics.sh

    - name: Download metrics
      ansible.builtin.fetch:
        src: "~/{{ inventory_hostname }}.metrics"
        flat: true
        dest: "../metrics/"

- name: Assemble metrics into one file
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Assemble metrics
      ansible.builtin.assemble:
        src: ../metrics
        dest: ../assembled.metrics
        mode: "644"
