- name: Prepare ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Generate node environments
      changed_when: true
      ansible.builtin.command:
        cmd: ./configure.sh

    - name: Create metrics directory
      ansible.builtin.file:
        path: metrics
        state: directory
        mode: "0755"

- name: Prepare fledger nodes
  hosts: nodes
  become: true
  tasks:
    - name: Stop nodes
      ansible.builtin.script: ../playbook/stopnodes.sh

    - name: Copy files
      ansible.builtin.copy:
        src: ~/fledger
        dest: ~/
        mode: preserve
      loop:
        - ~/fledger
        - ../playbook/fledger.service

    - name: Copy environment
      ansible.builtin.copy:
        src: "env.systemd/{{ inventory_hostname }}/"
        dest: ~/env.systemd
        mode: preserve

- name: Prepare central node
  hosts: central
  become: true
  tasks:
    - name: Disable ip forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 0
        sysctl_set: true
        state: present
        reload: true

    - name: Copy binaries
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/
        mode: preserve
      loop:
        - ~/fledger
        - ~/flsignal

    - name: Copy services
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        mode: preserve
      loop:
        - flsignal.service
        - flrealm.service

    - name: Stop services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: stopped
        daemon_reload: true
      loop:
        - flsignal
        - flrealm

    - name: Remove logs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/log/flsignal
        - /var/log/flrealm

    - name: Start services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: restarted
      loop:
        - flsignal
        - flrealm

- name: Run the simulation
  hosts: nodes
  become: true
  timeout: 10 # 300
  tasks:
    - name: Start nodes
      ansible.builtin.script: ../playbook/startnodes.sh

    - name: Wait for simulation end
      ansible.builtin.script: ../playbook/waitnodes.sh


# Must remain separate so it runs even if the simulation fails
- name: Download metrics
  hosts: nodes
  become: true
  tasks:
    - name: Find fledger services
      ansible.builtin.find:
        paths: ~/env.systemd
      register: fledger_services

    - name: Download metrics
      ansible.builtin.fetch:
        src: "/tmp/{{ item.path | basename }}.metrics"
        flat: true
        dest: "metrics/"
      loop: "{{ fledger_services | dict2items }}"

- name: Assemble metrics into one file
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Assemble metrics
      ansible.builtin.assemble:
        src: metrics
        dest: assembled.metrics
        mode: "644"
