- name: Setup for all nodes
  hosts: all
  become: true
  tasks:
    - name: Copy executable to nodes
      ansible.builtin.copy:
        src: "~/{{ item }}"
        dest: ~/
        mode: preserve
      loop:
        - fledger
        - flsignal

    - name: Remove config folders and logs
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - /root/flnode
        - /var/log/fledger-recv
        - /var/log/fledger-send

- name: Setup node a
  hosts: a
  become: true
  tasks:
    - name: Copy signaling service
      ansible.builtin.copy:
        src: flsignal.service
        dest: /etc/systemd/system/
        mode: preserve
    - name: Copy fledger service (send)
      ansible.builtin.copy:
        src: fledger-send.service
        dest: /etc/systemd/system/
        mode: preserve
    - name: Start signaling server
      ansible.builtin.systemd_service:
        name: flsignal
        state: restarted
        daemon_reload: true
        no_block: true
    - name: Start fledger node (send)
      ansible.builtin.systemd_service:
        name: fledger-send
        state: restarted
        no_block: true

- name: Setup node b
  hosts: b
  become: true
  tasks:
    - name: Copy fledger service (recv)
      ansible.builtin.copy:
        src: fledger-recv.service
        dest: /etc/systemd/system/
        mode: preserve
    - name: Start fledger node (recv)
      ansible.builtin.systemd_service:
        name: fledger-recv
        state: restarted
        daemon_reload: true
        no_block: true
    - name: Wait for message received on fledger node (recv)
      ansible.builtin.wait_for:
        path: /var/log/fledger-recv
        search_regex: "RECV_CHAT_MSG TRIGGERED"
        timeout: 10
