- name: Prepare ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Generate node environments
      changed_when: true
      ansible.builtin.command:
        cmd: ./generate-env.sh

    - name: Create metrics directory
      ansible.builtin.file:
        path: metrics
        state: directory
        mode: "0755"

- name: Prepare fledger nodes
  hosts: nodes
  become: true
  tasks:
    - name: Copy binary
      ansible.builtin.copy:
        src: ~/fledger
        dest: ~/
        mode: preserve

    - name: Copy service
      ansible.builtin.copy:
        src: fledger.service
        dest: /etc/systemd/system/
        mode: preserve

    - name: Stop service
      ansible.builtin.systemd_service:
        name: fledger
        state: stopped
        daemon_reload: true

    - name: Copy environment
      ansible.builtin.copy:
        src: "env.systemd/{{ inventory_hostname }}.env"
        dest: ~/env.systemd
        mode: preserve

    - name: Remove old node and logs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /root/flnode
        - /var/log/fledger


- name: Prepare central node
  hosts: central
  become: true
  tasks:
    - name: Disable ip forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 0
        sysctl_set: true
        state: present
        reload: true

    - name: Copy flsignal binary
      ansible.builtin.copy:
        src: ~/flsignal
        dest: ~/
        mode: preserve

    - name: Copy flsignal service
      ansible.builtin.copy:
        src: flsignal.service
        dest: /etc/systemd/system/
        mode: preserve

    - name: Stop flsignal
      ansible.builtin.systemd_service:
        name: flsignal
        state: stopped
        daemon_reload: true

    - name: Remove flsignal logs
      ansible.builtin.file:
        path: /var/log/flsignal
        state: absent

    - name: Start flsignal
      ansible.builtin.systemd_service:
        name: flsignal
        state: restarted

- name: Run the simulation
  hosts: nodes
  become: true
  timeout: 300
  tasks:
    - name: Start fledger
      ansible.builtin.systemd_service:
        name: fledger
        state: restarted
        daemon_reload: true

    - name: Wait for success trigger
      ansible.builtin.wait_for:
        path: /var/log/fledger
        search_regex: "RECV_CHAT_MSG TRIGGERED"

# Must remain separate so it runs even if the simulation fails
- name: Download metrics
  hosts: nodes
  become: true
  tasks:
    - name: Download metrics
      ansible.builtin.fetch:
        src: /tmp/out.metrics
        flat: true
        dest: "metrics/{{ inventory_hostname }}.metrics"

- name: Assemble metrics into one file
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Assemble metrics
      ansible.builtin.assemble:
        src: metrics
        dest: assembled.metrics
        mode: "644"
